// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/GuguLH/gin-spark/internal/repository"
	"github.com/GuguLH/gin-spark/internal/repository/dao"
	"github.com/GuguLH/gin-spark/internal/service"
	"github.com/GuguLH/gin-spark/internal/web"
	"github.com/GuguLH/gin-spark/ioc"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	v := ioc.InitGinMiddlewares()
	db := ioc.InitDB()
	iStudentDAO := dao.NewGormStudentDAO(db)
	iStudentRepository := repository.NewStudentRepository(iStudentDAO)
	iStudentService := service.NewStudentService(iStudentRepository)
	logger := ioc.InitLogger()
	studentHandler := web.NewStudentHandler(iStudentService, logger)
	engine := ioc.InitWebServer(v, studentHandler)
	return engine
}

// wire.go:

// 第三方依赖
var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitLogger)

// Web服务
var webSet = wire.NewSet(ioc.InitGinMiddlewares, ioc.InitWebServer)

// Student服务
var studentSet = wire.NewSet(web.NewStudentHandler, service.NewStudentService, repository.NewStudentRepository, dao.NewGormStudentDAO)
